export const defaultTheme = {
  colors: {
    'yellow-dark': '#c47f17',
    yellow: '#dbac2c',
    'yellow-light': '#f1E9C9',
    'purple-dark': '#4B2995',
    purple: '#8047f8',
    'purple-light': '#ebe5f9',
    'base-title': '#272221',
    'base-subtitles': '#403937',
    'base-text': '#574f4d',
    'base-label': '#8D8686',
    'base-hover': '#d7d5d5',
    'base-button': '#e6e5e5',
    'base-input': '#ededed',
    'base-card': '#f3f2f2',
    background: '#fafafa',
    white: '#ffffff',
    'base-error': '#f84747',
  },
  textSizes: {
    'title-extra-large': '3rem',
    'title-large': '2rem',
    'title-medium': '1.5rem',
    'title-small': '1.2rem',
    'title-extra-small': '1.125rem',
    'text-regular-large': '1.25rem',
    'text-bold-large': '1.25rem',
    'text-regular-medium': '1rem',
    'text-bold-medium': '1rem',
    'text-regular-small': '0.875rem',
    'text-bold-small': '0.75rem',
    'components-tag': '0.625rem',
    'components-button-g': '0.875rem',
    'components-button-s': '0.75rem',
  },
  fonts: {
    regular: "'Roboto'",
    title: "'Baloo 2'",
  },
}
